name: CI

on:
  push:
  pull_request:

jobs:
  test-minimal-args:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
        - uses: actions/checkout@v4
    
        - id: name-gen
          uses: ./ # Use the action

        - run: | 
            size=$(echo ${{ steps.name-gen.outputs.generated-name }} | wc -m)
            if [ $size -lt 4 ]; then
                echo "Resulting name was too small got ${{ steps.name-gen.outputs.generated-name }} with size $size"
                exit 1;
            fi
          shell: bash
